Repository Akatsuki-USW/Buzzzzing-Server, pull requests merged in 2023-07, with the labels that each got.

#16 [WBS1-79] Aws S3 유효성 검사 파트 리팩토링
  gradlew
  src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/util/s3/S3SaveDir.java
  src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java
  src/main/java/bokjak/bokjakserver/util/s3/dto/AwsS3Dto.java
  src/main/java/bokjak/bokjakserver/util/s3/service/AwsS3Service.java
Labels: 🛠 refactoring

#17 [WBS1-185][WBS1-184] SleepingUser
  build.gradle
  src/main/java/bokjak/bokjakserver/BokjakserverApplication.java
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/domain/report/model/Report.java
  src/main/java/bokjak/bokjakserver/domain/report/model/ReportTarget.java
  src/main/java/bokjak/bokjakserver/domain/report/model/ReportedTarget.java
  src/main/java/bokjak/bokjakserver/domain/user/model/SleepingUser.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
  src/main/java/bokjak/bokjakserver/domain/user/model/UserStatus.java
  src/main/java/bokjak/bokjakserver/domain/user/repository/SleepingUserRepository.java
  src/main/java/bokjak/bokjakserver/domain/user/repository/UserBlockUserRepository.java
  src/main/java/bokjak/bokjakserver/domain/user/repository/UserRepository.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
  src/main/java/bokjak/bokjakserver/domain/user/service/SleepingUserService.java
  src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java
  src/main/resources/templates/convertSleepingMail.html
  src/test/java/bokjak/bokjakserver/domain/user/UserTemplate.java
  src/test/java/bokjak/bokjakserver/domain/user/service/UserServiceTest.java
Labels: 📝 feature, 🛠 refactoring

#19 feat: 유저 프로필 업데이트 추가
  src/main/java/bokjak/bokjakserver/domain/notification/model/Notification.java
  src/main/java/bokjak/bokjakserver/domain/notification/model/NotificationType.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
  src/main/java/bokjak/bokjakserver/domain/user/dto/UserDto.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
  src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java
Labels: 📝 feature

#22 chore: 디스플레이명 변경
  src/main/java/bokjak/bokjakserver/common/dummy/DummySpotCategory.java
  src/main/java/bokjak/bokjakserver/domain/category/dto/CategoryDto.java
  src/main/java/bokjak/bokjakserver/domain/category/dto/CheckBoxFilter.java
  src/main/java/bokjak/bokjakserver/domain/category/dto/CongestionHistoricalDateChoice.java
  src/main/java/bokjak/bokjakserver/util/enums/EnumQueryValue.java
Labels: minor

#23 [WBS1-123] feat: 신고 생성
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
  src/main/java/bokjak/bokjakserver/domain/report/controller/ReportController.java
  src/main/java/bokjak/bokjakserver/domain/report/dto/ReportDto.java
  src/main/java/bokjak/bokjakserver/domain/report/model/Report.java
  src/main/java/bokjak/bokjakserver/domain/report/repository/ReportRepository.java
  src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepository.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
Labels: 📝 feature

#26 feat: CICD 환경 변수 설정
  Dockerfile
  build.gradle
Labels: 📝 feature, minor

#25 feat: 로케이션 테스트 코드
  src/main/java/bokjak/bokjakserver/config/security/PrincipalDetails.java
  src/main/java/bokjak/bokjakserver/domain/location/controller/LocationController.java
  src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
  src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java
  src/test/java/bokjak/bokjakserver/domain/location/LocationMockUtils.java
  src/test/java/bokjak/bokjakserver/domain/location/LocationServiceTest.java
Labels: 📝 feature, minor

#32 style: 선택지 박스 업데이트
  src/main/java/bokjak/bokjakserver/common/dummy/CategoryDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/DummyLocationCategory.java
  src/main/java/bokjak/bokjakserver/domain/category/dto/CongestionLevelChoice.java
Labels: :waffle: minor

#33 [WBS1-187] Feature/fcm
  .gitignore
  build.gradle
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/config/WebConfig.java
  src/main/java/bokjak/bokjakserver/domain/notification/controller/NotificationController.java
  src/main/java/bokjak/bokjakserver/domain/notification/dto/FcmDto.java
  src/main/java/bokjak/bokjakserver/domain/notification/dto/NotificationDto.java
  src/main/java/bokjak/bokjakserver/domain/notification/exception/NotificationException.java
  src/main/java/bokjak/bokjakserver/domain/notification/model/NotificationType.java
  src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepository.java
  src/main/java/bokjak/bokjakserver/domain/notification/service/FcmService.java
  src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
  src/main/java/bokjak/bokjakserver/domain/test/TestController.java
  src/main/java/bokjak/bokjakserver/domain/user/dto/AuthDto.java
  src/main/java/bokjak/bokjakserver/domain/user/dto/UserDto.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
Labels: 📝 feature

#36 fix: 날짜 계산 오류
  src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
  src/main/java/bokjak/bokjakserver/domain/category/dto/CongestionHistoricalDateChoice.java
  src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
  src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
Labels: 💦 fixed

#37 feat: 잘못된 url exception
  src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
Labels: 📝 feature

#35 [WBS1-81] 스팟 API 구현
  src/main/java/bokjak/bokjakserver/common/constant/ConstraintConstants.java
  src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
  src/main/java/bokjak/bokjakserver/common/dto/ApiResponse.java
  src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/domain/bookmark/repository/SpotBookmarkRepository.java
  src/main/java/bokjak/bokjakserver/domain/category/model/LocationCategory.java
  src/main/java/bokjak/bokjakserver/domain/category/model/SpotCategory.java
  src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
  src/main/java/bokjak/bokjakserver/domain/congestion/model/Congestion.java
  src/main/java/bokjak/bokjakserver/domain/location/controller/LocationController.java
  src/main/java/bokjak/bokjakserver/domain/location/dto/LocationDto.java
  src/main/java/bokjak/bokjakserver/domain/location/model/Location.java
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
  src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
  src/main/java/bokjak/bokjakserver/domain/spot/dto/SpotDto.java
  src/main/java/bokjak/bokjakserver/domain/spot/exception/SpotException.java
  src/main/java/bokjak/bokjakserver/domain/spot/model/Spot.java
  src/main/java/bokjak/bokjakserver/domain/spot/model/SpotImage.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepository.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/spot/service/SpotService.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
  src/main/java/bokjak/bokjakserver/util/s3/dto/AwsS3Dto.java
Labels: 📝 feature

#39 [WBS1-260] 스웨거 명세
  src/main/java/bokjak/bokjakserver/common/HelloController.java
  src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
  src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
  src/main/java/bokjak/bokjakserver/config/swagger/SwaggerConfig.java
  src/main/java/bokjak/bokjakserver/config/swagger/SwaggerController.java
  src/main/java/bokjak/bokjakserver/domain/category/controller/CategoryController.java
  src/main/java/bokjak/bokjakserver/domain/location/controller/LocationController.java
  src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
  src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java
Labels: 📝 feature

#38 fix: 로케이션 존재 여부 검사
  src/main/java/bokjak/bokjakserver/domain/bookmark/repository/SpotBookmarkRepository.java
  src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
  src/main/java/bokjak/bokjakserver/domain/spot/dto/SpotDto.java
  src/main/java/bokjak/bokjakserver/domain/spot/service/SpotService.java
  src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java
  src/main/java/bokjak/bokjakserver/util/s3/service/AwsS3Service.java
Labels: 💦 fixed, :sloth: chill

#40 [WBS1-82] 스팟 댓글 API 구현
  src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/domain/comment/controller/CommentController.java
  src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
  src/main/java/bokjak/bokjakserver/domain/comment/exception/CommentException.java
  src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
  src/main/java/bokjak/bokjakserver/domain/spot/controller/SpotController.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/spot/service/SpotService.java
Labels: 📝 feature

#41 fix: 로케이션 ORDER BY id 누락
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryImpl.java
Labels: 💦 fixed
