Repository Akatsuki-USW/Buzzzzing-Server, pull requests merged in 2023-08, with the labels that each got.

#42 Feature/swagger
  src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
  src/main/java/bokjak/bokjakserver/config/AsyncConfig.java
  src/main/java/bokjak/bokjakserver/domain/notification/controller/NotificationController.java
  src/main/java/bokjak/bokjakserver/domain/notification/dto/NotificationDto.java
  src/main/java/bokjak/bokjakserver/domain/notification/service/FcmService.java
  src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
  src/main/java/bokjak/bokjakserver/domain/report/controller/ReportController.java
  src/main/java/bokjak/bokjakserver/domain/report/dto/ReportDto.java
  src/main/java/bokjak/bokjakserver/domain/test/TestController.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/AuthController.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
  src/main/java/bokjak/bokjakserver/domain/user/dto/AuthDto.java
  src/main/java/bokjak/bokjakserver/domain/user/service/SleepingUserService.java
  src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
Labels: 📝 feature, 🛠 refactoring

#45 refactor: yml 분리
  .github/workflows/deploy.yml
  .github/workflows/pr-test.yml
  .gitignore
  Dockerfile
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🛠 refactoring

#46 !HOTFIX: 배포시 깃허브 환경변수 YML 추가
  .github/workflows/deploy.yml
  src/main/resources/application-dev.yml
Labels: 💦 fixed

#43 [WBS1-287] 스팟 대댓글 API
  src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
  src/main/java/bokjak/bokjakserver/common/dummy/CommentDummy.java
  src/main/java/bokjak/bokjakserver/domain/comment/controller/CommentController.java
  src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
  src/main/java/bokjak/bokjakserver/domain/comment/model/Comment.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
Labels: 📝 feature

#44 refactor: loginUser 정보 가져오기
  src/main/java/bokjak/bokjakserver/domain/notification/controller/NotificationController.java
  src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
  src/main/java/bokjak/bokjakserver/domain/report/controller/ReportController.java
  src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java
  src/main/java/bokjak/bokjakserver/domain/test/TestController.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/AuthController.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
  src/main/java/bokjak/bokjakserver/domain/user/service/UserService.java
  src/test/java/bokjak/bokjakserver/domain/user/service/UserServiceTest.java
Labels: 🛠 refactoring

#48 refactor: gitignore dev, prod YML
  .gitignore
  src/main/resources/application.yml
Labels: 🛠 refactoring

#47 docs: README 꾸밈
  README.md
Labels: :sloth: chill

#52 minor: Django API 연동 준비 (아직은 개발용)
  src/main/java/bokjak/bokjakserver/common/dummy/CongestionDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/LocationDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
Labels: :waffle: minor

#50 fix: 댓글, 대댓글 오래된 순으로 수정 + totalElements 오류 해결
  src/main/java/bokjak/bokjakserver/common/dto/PageResponse.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
  src/main/java/bokjak/bokjakserver/util/CustomSliceExecutionUtils.java
Labels: 💦 fixed

#53 fix: slice limit +1 누락
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/util/CustomSliceExecutionUtils.java
Labels: 💦 fixed

#54 feat: comment 작성시 알림
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
  src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
  src/main/java/bokjak/bokjakserver/domain/notification/dto/NotificationDto.java
Labels: 📝 feature

#57 chore: gitignore 더미 파일
  .gitignore
Labels: :waffle: minor, :sloth: chill

#58 refactor: S3 업데이트 편의성
  src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
  src/main/java/bokjak/bokjakserver/util/s3/controller/AwsS3Controller.java
  src/main/java/bokjak/bokjakserver/util/s3/dto/AwsS3Dto.java
  src/main/java/bokjak/bokjakserver/util/s3/service/AwsS3Service.java
Labels: 🛠 refactoring

#60 Feature/admin
  src/main/java/bokjak/bokjakserver/common/constant/SwaggerConstants.java
  src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
  src/main/java/bokjak/bokjakserver/common/exception/StatusCode.java
  src/main/java/bokjak/bokjakserver/config/jwt/JwtProvider.java
  src/main/java/bokjak/bokjakserver/domain/report/dto/ReportDto.java
  src/main/java/bokjak/bokjakserver/domain/report/model/Report.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/AuthController.java
  src/main/java/bokjak/bokjakserver/domain/user/dto/AuthDto.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
Labels: 📝 feature

#61 refactor: 회원 탈퇴
  src/main/java/bokjak/bokjakserver/domain/user/service/KakaoService.java
Labels: 🛠 refactoring

#62 Refactor/user
  src/main/java/bokjak/bokjakserver/domain/user/model/BlackList.java
  src/main/java/bokjak/bokjakserver/domain/user/model/SleepingUser.java
  src/main/java/bokjak/bokjakserver/domain/user/model/User.java
  src/main/java/bokjak/bokjakserver/domain/user/repository/BlackListRepository.java
  src/main/java/bokjak/bokjakserver/domain/user/repository/SleepingUserRepository.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
  src/main/java/bokjak/bokjakserver/domain/user/service/SleepingUserService.java
Labels: 🛠 refactoring

#63 fix: 혼잡도 일간 통계 9시 이후 데이터만 응답
  src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
  src/main/java/bokjak/bokjakserver/domain/ban/dto/BanDto.java
  src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
  src/main/java/bokjak/bokjakserver/domain/congestion/dto/CongestionDto.java
  src/main/java/bokjak/bokjakserver/domain/notification/dto/NotificationDto.java
  src/main/java/bokjak/bokjakserver/domain/spot/dto/SpotDto.java
  src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
Labels: 💦 fixed

#66 Refactor/user
  src/main/java/bokjak/bokjakserver/domain/report/controller/ReportController.java
  src/main/java/bokjak/bokjakserver/domain/report/dto/ReportDto.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/AuthController.java
  src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
  src/main/java/bokjak/bokjakserver/domain/user/dto/AuthDto.java
  src/main/java/bokjak/bokjakserver/domain/user/service/AuthService.java
Labels: 🛠 refactoring

#67 refactor: queryDsl 적용
  src/main/java/bokjak/bokjakserver/domain/ban/repository/BanRepository.java
  src/main/java/bokjak/bokjakserver/domain/ban/repository/BanRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/ban/repository/BanRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/ban/service/BanService.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepository.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
  src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepository.java
  src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
Labels: 🛠 refactoring

#64 minor: 변경된 AWS 지역 S3 URL 반영
  src/main/java/bokjak/bokjakserver/common/dummy/DummyLocationCategory.java
  src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/UserDummy.java
  src/test/java/bokjak/bokjakserver/domain/location/LocationMockUtils.java
Labels: :waffle: minor
