Repository Akatsuki-USW/Buzzzzing-Server, pull requests merged in 2023-09, with the labels that each got.

#77 fix: 탈퇴 유저 필드 null 응답 오류
  src/main/java/bokjak/bokjakserver/domain/comment/dto/CommentDto.java
  src/main/java/bokjak/bokjakserver/domain/spot/dto/SpotDto.java
  src/main/java/bokjak/bokjakserver/util/web/PreventNullResponseUtils.java
Labels: 💦 fixed

#72 refactor: 특정 프로파일(local)에서만 더미 파일 작동하도록 변경
  .gitignore
  src/main/java/bokjak/bokjakserver/common/dummy/BuzzingDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/CategoryDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/CommentDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/CongestionDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/LocationDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/SpotDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/UserDummy.java
Labels: 🛠 refactoring

#71 feat: 실배포 프로파일(prod) CloudWatch 로그 기능 추가
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 📝 feature

#69 실배포용으로 CICD 파일 변경
  .github/workflows/deploy.yml
  Dockerfile
Labels: 📝 feature

#78 Update README.md
  README.md
Labels: 📜 docs

#81 fix: report 중복 접수
  src/main/java/bokjak/bokjakserver/domain/report/repository/ReportRepository.java
  src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java
Labels: 💦 fixed

#82 fix: 중복 신고 오류 개선
  README.md
  src/main/java/bokjak/bokjakserver/domain/report/repository/ReportRepository.java
  src/main/java/bokjak/bokjakserver/domain/report/service/ReportService.java
Labels: 💦 fixed

#84 API 요청 로깅
  build.gradle
  src/main/java/bokjak/bokjakserver/BokjakserverApplication.java
  src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
  src/main/java/bokjak/bokjakserver/domain/test/TestController.java
  src/main/java/bokjak/bokjakserver/util/CustomSliceExecutionUtils.java
  src/main/java/bokjak/bokjakserver/web/log/LoggerAspect.java
  src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapper.java
  src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapperFilter.java
Labels: 📝 feature

#89 hotfix: 댓글 수정 작성자 여부 검사 누락
  src/main/java/bokjak/bokjakserver/domain/comment/service/CommentService.java
Labels: 💦 fixed

#87 style: Filter, SerurityConfig 코드 정리
  src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
  src/main/java/bokjak/bokjakserver/config/security/SecurityConfig.java
  src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapper.java
  src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapperFilter.java
Labels: :waffle: minor

#86 release: #84 #87
  build.gradle
  src/main/java/bokjak/bokjakserver/BokjakserverApplication.java
  src/main/java/bokjak/bokjakserver/common/constant/GlobalConstants.java
  src/main/java/bokjak/bokjakserver/common/exception/GlobalExceptionHandler.java
  src/main/java/bokjak/bokjakserver/config/security/SecurityConfig.java
  src/main/java/bokjak/bokjakserver/domain/test/TestController.java
  src/main/java/bokjak/bokjakserver/util/CustomSliceExecutionUtils.java
  src/main/java/bokjak/bokjakserver/web/log/LoggerAspect.java
  src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapper.java
  src/main/java/bokjak/bokjakserver/web/log/ReadableRequestBodyWrapperFilter.java
Labels: 📝 feature

#91 hotfix: 로케이션 리스트 조회 쿼리 수행 5초 문제
  src/main/java/bokjak/bokjakserver/common/dummy/CongestionDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/LocationDummy.java
  src/main/java/bokjak/bokjakserver/domain/congestion/repository/CongestionRepository.java
  src/main/java/bokjak/bokjakserver/domain/location/dto/LocationDto.java
  src/main/java/bokjak/bokjakserver/domain/location/model/Location.java
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
Labels: 🚑 fixed, 🏇 optimize

#90 fix: 코멘트 ORDER BY 오류
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java
Labels: 🛠 refactoring, 🚑 fixed

#92 release: #90 #91
  src/main/java/bokjak/bokjakserver/common/dummy/CongestionDummy.java
  src/main/java/bokjak/bokjakserver/common/dummy/LocationDummy.java
  src/main/java/bokjak/bokjakserver/domain/congestion/repository/CongestionRepository.java
  src/main/java/bokjak/bokjakserver/domain/location/dto/LocationDto.java
  src/main/java/bokjak/bokjakserver/domain/location/model/Location.java
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryCustom.java
  src/main/java/bokjak/bokjakserver/domain/location/repository/LocationRepositoryImpl.java
  src/main/java/bokjak/bokjakserver/domain/location/service/LocationService.java
  src/main/java/bokjak/bokjakserver/domain/spot/repository/SpotRepositoryImpl.java
Labels: 🚀release
